import { ClerkProvider } from "@clerk/nextjs"
import "../globals.css"
import { Inter } from "next/font/google"

import LeftSideBar from "@constants/layout/LeftSideBar"
import MainContainer from "@constants/layout/MainContainer"
import RightSideBar from "@constants/layout/RightSideBar"
import TopBar from "@constants/layout/TopBar"
import BottomBar from "@constants/layout/BottomBar"

export const metadata = {
  title: 'bingoland',
  description: 'Generated by Next.js',
}

const inter = Inter({subsets: ['latin']});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-purple-2 text-light-1`}>
          <main className="flex flex-row">
          <LeftSideBar />
          <MainContainer>
            {children}
          </MainContainer>
          <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
    
  )
}
